import { TestResult } from '../types';

export const COLORS = {
  primary: '#8B6B8B',
  warning: '#3D84B5',
  danger: '#C9956A',
  background: '#FDF6EE',
  surface: '#FFFAF5',
  tabBar: '#F5EDE3',
  border: '#E5D4C5',
  tabActive: '#8B6B8B',
  tabInactive: '#B8A89A',
};

export const ANALYZING_DURATION_MS = 3000;

export const TEST_TYPE_LABELS: Record<string, string> = {
  mom_urine: "Mom's Urine",
  breastmilk: 'Breastmilk',
  baby_urine: "Baby's Urine",
};

export const FAKE_TEST_RESULTS: TestResult[] = [
  {
    id: 'test-001',
    date: '2026-03-05',
    testType: 'mom_urine',
    biomarkers: [
      {
        name: 'specific_gravity',
        displayName: 'Specific Gravity',
        unit: 'g/mL',
        detected: 1.03,
        normalMin: 1.005,
        normalMax: 1.025,
        level: 'high',
      },
      {
        name: 'ketones',
        displayName: 'Ketones',
        unit: 'mg/dL',
        detected: 5,
        normalMin: 0,
        normalMax: 10,
        level: 'normal',
      },
      {
        name: 'vitamin_c',
        displayName: 'Vitamin C',
        unit: 'mg/dL',
        detected: 4,
        normalMin: 10,
        normalMax: 40,
        level: 'low',
      },
      {
        name: 'protein',
        displayName: 'Protein',
        unit: 'mg/dL',
        detected: 20,
        normalMin: 0,
        normalMax: 14,
        level: 'high',
      },
      {
        name: 'calcium_magnesium',
        displayName: 'Calcium/Magnesium',
        unit: 'mg/L',
        detected: 85,
        normalMin: 100,
        normalMax: 300,
        level: 'low',
      },
      {
        name: 'ph_level',
        displayName: 'pH Level',
        unit: 'pH',
        detected: 6.2,
        normalMin: 4.5,
        normalMax: 8.0,
        level: 'normal',
      },
    ],
  },
  {
    id: 'test-002',
    date: '2026-03-01',
    testType: 'breastmilk',
    biomarkers: [
      {
        name: 'alcohol',
        displayName: 'Alcohol',
        unit: 'mg/dL',
        detected: 0,
        normalMin: 0,
        normalMax: 0,
        level: 'normal',
      },
      {
        name: 'ph_level',
        displayName: 'pH Level',
        unit: 'pH',
        detected: 7.2,
        normalMin: 6.5,
        normalMax: 7.5,
        level: 'normal',
      },
      {
        name: 'vitamin_c',
        displayName: 'Vitamin C',
        unit: 'mg/dL',
        detected: 2.5,
        normalMin: 3,
        normalMax: 8,
        level: 'low',
      },
    ],
  },
  {
    id: 'test-003',
    date: '2026-02-25',
    testType: 'baby_urine',
    biomarkers: [
      {
        name: 'specific_gravity',
        displayName: 'Specific Gravity',
        unit: 'g/mL',
        detected: 1.008,
        normalMin: 1.001,
        normalMax: 1.018,
        level: 'normal',
      },
      {
        name: 'ketones',
        displayName: 'Ketones',
        unit: 'mg/dL',
        detected: 8,
        normalMin: 0,
        normalMax: 5,
        level: 'high',
      },
    ],
  },
  {
    id: 'test-004',
    date: '2026-02-18',
    testType: 'breastmilk',
    biomarkers: [
      {
        name: 'alcohol',
        displayName: 'Alcohol',
        unit: 'mg/dL',
        detected: 4,
        normalMin: 0,
        normalMax: 0,
        level: 'high',
      },
      {
        name: 'ph_level',
        displayName: 'pH Level',
        unit: 'pH',
        detected: 7.8,
        normalMin: 6.5,
        normalMax: 7.5,
        level: 'high',
      },
      {
        name: 'vitamin_c',
        displayName: 'Vitamin C',
        unit: 'mg/dL',
        detected: 5.5,
        normalMin: 3,
        normalMax: 8,
        level: 'normal',
      },
    ],
  },
  {
    id: 'test-005',
    date: '2026-02-10',
    testType: 'mom_urine',
    biomarkers: [
      {
        name: 'specific_gravity',
        displayName: 'Specific Gravity',
        unit: 'g/mL',
        detected: 1.02,
        normalMin: 1.005,
        normalMax: 1.025,
        level: 'normal',
      },
      {
        name: 'ketones',
        displayName: 'Ketones',
        unit: 'mg/dL',
        detected: 12,
        normalMin: 0,
        normalMax: 10,
        level: 'high',
      },
      {
        name: 'vitamin_c',
        displayName: 'Vitamin C',
        unit: 'mg/dL',
        detected: 18,
        normalMin: 10,
        normalMax: 40,
        level: 'normal',
      },
      {
        name: 'protein',
        displayName: 'Protein',
        unit: 'mg/dL',
        detected: 8,
        normalMin: 0,
        normalMax: 14,
        level: 'normal',
      },
      {
        name: 'calcium_magnesium',
        displayName: 'Calcium/Magnesium',
        unit: 'mg/L',
        detected: 210,
        normalMin: 100,
        normalMax: 300,
        level: 'normal',
      },
      {
        name: 'ph_level',
        displayName: 'pH Level',
        unit: 'pH',
        detected: 6.8,
        normalMin: 4.5,
        normalMax: 8.0,
        level: 'normal',
      },
    ],
  },
  {
    id: 'test-006',
    date: '2026-02-03',
    testType: 'baby_urine',
    biomarkers: [
      {
        name: 'specific_gravity',
        displayName: 'Specific Gravity',
        unit: 'g/mL',
        detected: 1.004,
        normalMin: 1.001,
        normalMax: 1.018,
        level: 'normal',
      },
      {
        name: 'ketones',
        displayName: 'Ketones',
        unit: 'mg/dL',
        detected: 2,
        normalMin: 0,
        normalMax: 5,
        level: 'normal',
      },
    ],
  },
  {
    id: 'test-007',
    date: '2026-01-27',
    testType: 'mom_urine',
    biomarkers: [
      {
        name: 'specific_gravity',
        displayName: 'Specific Gravity',
        unit: 'g/mL',
        detected: 1.022,
        normalMin: 1.005,
        normalMax: 1.025,
        level: 'normal',
      },
      {
        name: 'ketones',
        displayName: 'Ketones',
        unit: 'mg/dL',
        detected: 18,
        normalMin: 0,
        normalMax: 10,
        level: 'high',
      },
      {
        name: 'vitamin_c',
        displayName: 'Vitamin C',
        unit: 'mg/dL',
        detected: 9,
        normalMin: 10,
        normalMax: 40,
        level: 'low',
      },
      {
        name: 'protein',
        displayName: 'Protein',
        unit: 'mg/dL',
        detected: 25,
        normalMin: 0,
        normalMax: 14,
        level: 'high',
      },
      {
        name: 'calcium_magnesium',
        displayName: 'Calcium/Magnesium',
        unit: 'mg/L',
        detected: 70,
        normalMin: 100,
        normalMax: 300,
        level: 'low',
      },
      {
        name: 'ph_level',
        displayName: 'pH Level',
        unit: 'pH',
        detected: 5.8,
        normalMin: 4.5,
        normalMax: 8.0,
        level: 'normal',
      },
    ],
  },
  {
    id: 'test-008',
    date: '2026-01-20',
    testType: 'baby_urine',
    biomarkers: [
      {
        name: 'specific_gravity',
        displayName: 'Specific Gravity',
        unit: 'g/mL',
        detected: 1.012,
        normalMin: 1.001,
        normalMax: 1.018,
        level: 'normal',
      },
      {
        name: 'ketones',
        displayName: 'Ketones',
        unit: 'mg/dL',
        detected: 6,
        normalMin: 0,
        normalMax: 5,
        level: 'high',
      },
    ],
  },
  {
    id: 'test-009',
    date: '2026-01-13',
    testType: 'breastmilk',
    biomarkers: [
      {
        name: 'alcohol',
        displayName: 'Alcohol',
        unit: 'mg/dL',
        detected: 9,
        normalMin: 0,
        normalMax: 0,
        level: 'high',
      },
      {
        name: 'ph_level',
        displayName: 'pH Level',
        unit: 'pH',
        detected: 7.0,
        normalMin: 6.5,
        normalMax: 7.5,
        level: 'normal',
      },
      {
        name: 'vitamin_c',
        displayName: 'Vitamin C',
        unit: 'mg/dL',
        detected: 2.0,
        normalMin: 3,
        normalMax: 8,
        level: 'low',
      },
    ],
  },
  {
    id: 'test-010',
    date: '2026-01-06',
    testType: 'mom_urine',
    biomarkers: [
      {
        name: 'specific_gravity',
        displayName: 'Specific Gravity',
        unit: 'g/mL',
        detected: 1.015,
        normalMin: 1.005,
        normalMax: 1.025,
        level: 'normal',
      },
      {
        name: 'ketones',
        displayName: 'Ketones',
        unit: 'mg/dL',
        detected: 22,
        normalMin: 0,
        normalMax: 10,
        level: 'high',
      },
      {
        name: 'vitamin_c',
        displayName: 'Vitamin C',
        unit: 'mg/dL',
        detected: 6,
        normalMin: 10,
        normalMax: 40,
        level: 'low',
      },
      {
        name: 'protein',
        displayName: 'Protein',
        unit: 'mg/dL',
        detected: 30,
        normalMin: 0,
        normalMax: 14,
        level: 'high',
      },
      {
        name: 'calcium_magnesium',
        displayName: 'Calcium/Magnesium',
        unit: 'mg/L',
        detected: 55,
        normalMin: 100,
        normalMax: 300,
        level: 'low',
      },
      {
        name: 'ph_level',
        displayName: 'pH Level',
        unit: 'pH',
        detected: 5.5,
        normalMin: 4.5,
        normalMax: 8.0,
        level: 'normal',
      },
    ],
  },
  {
    id: 'test-011',
    date: '2025-12-29',
    testType: 'breastmilk',
    biomarkers: [
      {
        name: 'alcohol',
        displayName: 'Alcohol',
        unit: 'mg/dL',
        detected: 18,
        normalMin: 0,
        normalMax: 0,
        level: 'high',
      },
      {
        name: 'ph_level',
        displayName: 'pH Level',
        unit: 'pH',
        detected: 6.8,
        normalMin: 6.5,
        normalMax: 7.5,
        level: 'normal',
      },
      {
        name: 'vitamin_c',
        displayName: 'Vitamin C',
        unit: 'mg/dL',
        detected: 1.5,
        normalMin: 3,
        normalMax: 8,
        level: 'low',
      },
    ],
  },
  {
    id: 'test-012',
    date: '2025-12-22',
    testType: 'mom_urine',
    biomarkers: [
      {
        name: 'specific_gravity',
        displayName: 'Specific Gravity',
        unit: 'g/mL',
        detected: 1.018,
        normalMin: 1.005,
        normalMax: 1.025,
        level: 'normal',
      },
      {
        name: 'ketones',
        displayName: 'Ketones',
        unit: 'mg/dL',
        detected: 28,
        normalMin: 0,
        normalMax: 10,
        level: 'high',
      },
      {
        name: 'vitamin_c',
        displayName: 'Vitamin C',
        unit: 'mg/dL',
        detected: 3,
        normalMin: 10,
        normalMax: 40,
        level: 'low',
      },
      {
        name: 'protein',
        displayName: 'Protein',
        unit: 'mg/dL',
        detected: 35,
        normalMin: 0,
        normalMax: 14,
        level: 'high',
      },
      {
        name: 'calcium_magnesium',
        displayName: 'Calcium/Magnesium',
        unit: 'mg/L',
        detected: 40,
        normalMin: 100,
        normalMax: 300,
        level: 'low',
      },
      {
        name: 'ph_level',
        displayName: 'pH Level',
        unit: 'pH',
        detected: 5.2,
        normalMin: 4.5,
        normalMax: 8.0,
        level: 'normal',
      },
    ],
  },
];
